### ISSUE TITLE
Airflow image does not build in docker

### ISSUE THREAD

**Issue by alexraj84** [tuanavu/airflow-tutorial#23]
After cloning the repo and while firing up `docker-compose up` I do not get the airflow image build. I get the error `AttributeError: module 'sqlalchemy.dialects.postgresql' has no attribute 'MONEY'`

Here is the detailed error
```
postgres_1   | LOG:  incomplete startup packet
webserver_1  | [2019-09-07 22:39:56,209] {{settings.py:174}} INFO - setting.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800
webserver_1  | [2019-09-07 22:39:56,501] {{__init__.py:51}} INFO - Using executor LocalExecutor
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/bin/airflow", line 22, in <module>
webserver_1  |     from airflow.bin.cli import CLIFactory
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 68, in <module>
webserver_1  |     from airflow.www_rbac.app import cached_app as cached_app_rbac
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/www_rbac/app.py", line 25, in <module>
webserver_1  |     from flask_appbuilder import AppBuilder, SQLA
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/__init__.py", line 5, in <module>
webserver_1  |     from .base import AppBuilder
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/base.py", line 5, in <module>
webserver_1  |     from .api.manager import OpenApiManager
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/api/__init__.py", line 11, in <module>
webserver_1  |     from marshmallow_sqlalchemy.fields import Related, RelatedList
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/__init__.py", line 1, in <module>
webserver_1  |     from .schema import TableSchemaOpts, ModelSchemaOpts, TableSchema, ModelSchema
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/schema.py", line 3, in <module>
webserver_1  |     from .convert import ModelConverter
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/convert.py", line 36, in <module>
webserver_1  |     class ModelConverter:
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/convert.py", line 52, in ModelConverter
webserver_1  |     postgresql.MONEY: fields.Decimal,
webserver_1  | AttributeError: module 'sqlalchemy.dialects.postgresql' has no attribute 'MONEY'
webserver_1  | [2019-09-07 22:39:58,269] {{settings.py:174}} INFO - setting.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800
webserver_1  | [2019-09-07 22:39:58,284] {{settings.py:174}} INFO - setting.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800
webserver_1  | [2019-09-07 22:39:58,671] {{__init__.py:51}} INFO - Using executor LocalExecutor
webserver_1  | [2019-09-07 22:39:58,693] {{__init__.py:51}} INFO - Using executor LocalExecutor
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/bin/airflow", line 22, in <module>
webserver_1  |     from airflow.bin.cli import CLIFactory
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 68, in <module>
webserver_1  |     from airflow.www_rbac.app import cached_app as cached_app_rbac
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/www_rbac/app.py", line 25, in <module>
webserver_1  |     from flask_appbuilder import AppBuilder, SQLA
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/__init__.py", line 5, in <module>
webserver_1  |     from .base import AppBuilder
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/base.py", line 5, in <module>
webserver_1  |     from .api.manager import OpenApiManager
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/api/__init__.py", line 11, in <module>
webserver_1  |     from marshmallow_sqlalchemy.fields import Related, RelatedList
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/__init__.py", line 1, in <module>
webserver_1  |     from .schema import TableSchemaOpts, ModelSchemaOpts, TableSchema, ModelSchema
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/schema.py", line 3, in <module>
webserver_1  |     from .convert import ModelConverter
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/convert.py", line 36, in <module>
webserver_1  |     class ModelConverter:
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/convert.py", line 52, in ModelConverter
webserver_1  |     postgresql.MONEY: fields.Decimal,
webserver_1  | AttributeError: module 'sqlalchemy.dialects.postgresql' has no attribute 'MONEY'
webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/bin/airflow", line 22, in <module>
webserver_1  |     from airflow.bin.cli import CLIFactory
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 68, in <module>
webserver_1  |     from airflow.www_rbac.app import cached_app as cached_app_rbac
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/www_rbac/app.py", line 25, in <module>
webserver_1  |     from flask_appbuilder import AppBuilder, SQLA
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/__init__.py", line 5, in <module>
webserver_1  |     from .base import AppBuilder
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/base.py", line 5, in <module>
webserver_1  |     from .api.manager import OpenApiManager
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/api/__init__.py", line 11, in <module>
webserver_1  |     from marshmallow_sqlalchemy.fields import Related, RelatedList
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/__init__.py", line 1, in <module>
webserver_1  |     from .schema import TableSchemaOpts, ModelSchemaOpts, TableSchema, ModelSchema
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/schema.py", line 3, in <module>
webserver_1  |     from .convert import ModelConverter
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/convert.py", line 36, in <module>
webserver_1  |     class ModelConverter:
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/marshmallow_sqlalchemy/convert.py", line 52, in ModelConverter
webserver_1  |     postgresql.MONEY: fields.Decimal,
webserver_1  | AttributeError: module 'sqlalchemy.dialects.postgresql' has no attribute 'MONEY'
```

**Comment by laiunce** [comment]
Hello, Im having the same issue too. It was working fine days ago but now it is crashing.

**Comment by alexraj84** [comment]
Ok. looks like the first time it works for everyone and the second when it is restarted the process fails.

**Comment by laiunce** [comment]
The problem I think is that there were some changes in the docker images (puckel/docker-airflow:1.10.1 or postgres:9.6). I been doing some test for a month with this repo and it was working well.

**Comment by netnutmike** [comment]
I am having the same issue.  It failed for me on the first run though.

**Comment by mikekenneth** [comment]
Hi, Am also having the same error.. Did anybody find a workaround or another more stable image?

**Comment by bsewell** [comment]
Greetings - I just joined and am having the same issues. Airflow 1.10.1 shows it's restarting constantly and localhost:8080 fails. On the other hand, error logs show tons of postgres errors - AttributeError: module 'sqlalchemy.dialects.postgresql' has no attribute 'MONEY'

Checking on the docker log for postgres shows - "LOG:  incomplete startup packet"

Jist of the error message is derscribed here - https://www.postgresql-archive.org/Incomplete-startup-packet-help-needed-td5199030.html
Sounds like postgres is being hit with empty packets, possibly from the webserver restarting?

I'm running on Mac current OSX and trying to learn Airflow through your tutorials. I am excited to get past this blocker in order to start learning airflow.

**Comment by GomesNayagam** [comment]
i am having the same issue too  'sqlalchemy.dialects.postgresql' has no attribute 'MONEY'

**Comment by liu-du** [comment]
looks like the "github.com/puckel/docker-airflow.git" docker image installs the wrong sqlalchemy<1.2? the `MONEY` attribute is new in 1.2:

from my docker-compose build logs:
```
Collecting sqlalchemy<1.2.0,>=1.1.15 (from apache-airflow[celery,crypto,gcp_api,hive,jdbc,mysql,postgres,s3,ssh]==1.10.0)
  Downloading https://files.pythonhosted.org/packages/cc/4d/96d93ff77cd67aca7618e402191eee3490d8f5f245d6ab7622d35fe504f4/SQLAlchemy-1.1.18.tar.gz (5.3MB)
```
from sqlalchemy:
![image](https://user-images.githubusercontent.com/34998797/65086791-78993700-d9f6-11e9-8e6c-fc5418a0cfbd.png)
link: https://docs.sqlalchemy.org/en/13/dialects/postgresql.html

**Comment by liu-du** [comment]
ohh adding "PYTHON_DEPS: sqlalchemy==1.2.0" to docker-compose.yml seems to solve problem quick and dirty: 
![image](https://user-images.githubusercontent.com/34998797/65088440-b436ff80-d9fc-11e9-8b09-4747b42787b4.png)

it's a quick fix as there're some errors when building the image, but everything seems to be working...

**Comment by GomesNayagam** [comment]
i updated puckel/docker-airflow:1.10.4 and it works in windows. i had issue with config json which i loaded manually.

**Comment by bsewell** [comment]
I tried running the the update on Mac with airflow1.10.4 and PYTHON_DEPS added to the docker-compose.yml and still suffered from the same error messages above. 

I followed this article and was able to launch Airflow finally. To be fair, I'm brand new to all this and spent 6 hours just trying to get stuff to work. 

 https://medium.com/@segal.levi/using-docker-to-explore-airflow-and-other-open-source-projects-e6349ffadf5a

Check it out...

**Comment by GomesNayagam** [comment]
see if this link help, everything is baked in as VM, just install oracle virtual box and all done. https://marclamberti.com/form-course-material-100/

**Comment by robinparriath** [comment]
> ohh adding "PYTHON_DEPS: sqlalchemy==1.2.0" to docker-compose.yml seems to solve problem quick and dirty:
> ![image](https://user-images.githubusercontent.com/34998797/65088440-b436ff80-d9fc-11e9-8b09-4747b42787b4.png)
> 
> it's a quick fix as there're some errors when building the image, but everything seems to be working...

I forked the repo, made this change and it works.
I created a pull request (https://github.com/tuanavu/airflow-tutorial/pull/25) so, the change can be merged back, but in the meantime, you can test it on (https://github.com/robinparriath/airflow-tutorial).

**Comment by tuanavu** [comment]
Sorry for the late response. I was busy for the last 2 months.

Thanks @robinparriath for working on this issue. Confirming that adding `PYTHON_DEPS: sqlalchemy==1.2.0` to `docker-compose.yml` seems to solve issue.

The pull request is accepted.
