### ISSUE TITLE
Unable to launch the compose script

### ISSUE THREAD

**Issue by Desislav-Petrov** [tuanavu/airflow-tutorial#29]
I follow the instructions but after the docoker-compose up the service doesnt' come up.

Upon querying the logs I get the following: 

webserver_1  | Traceback (most recent call last):
webserver_1  |   File "/usr/local/bin/airflow", line 22, in <module>
webserver_1  |     from airflow.bin.cli import CLIFactory
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/bin/cli.py", line 68, in <module>
webserver_1  |     from airflow.www_rbac.app import cached_app as cached_app_rbac
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/www_rbac/app.py", line 25, in <module>
webserver_1  |     from flask_appbuilder import AppBuilder, SQLA
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/__init__.py", line 5, in <module>
webserver_1  |     from .base import AppBuilder
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/base.py", line 3, in <module>
webserver_1  |     from .views import IndexView, UtilView
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/views.py", line 8, in <module>
webserver_1  |     from .baseviews import BaseView, BaseCRUDView, BaseFormView, expose, expose_api
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/baseviews.py", line 7, in <module>
webserver_1  |     from .forms import GeneralModelConverter
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/forms.py", line 9, in <module>
webserver_1  |     from .fieldwidgets import (BS3TextAreaFieldWidget,
webserver_1  |   File "/usr/local/lib/python3.6/site-packages/flask_appbuilder/fieldwidgets.py", line 1, in <module>
webserver_1  |     from wtforms.widgets import HTMLString, html_params
webserver_1  | ImportError: cannot import name 'HTMLString'

Looks like an env issue to me - can u please advise?

Thanks

**Comment by boschmateo** [comment]
Same issue here. Been trying to fix it all day long.

**Comment by boschmateo** [comment]
There is a new Issue opened in [docker-airflow ](https://github.com/puckel/docker-airflow/issues/544).

**Comment by resdevd** [comment]
Or you can use this Docker compose boilerplate updated with official Airflow Docker images

https://github.com/resdevd/docker-compose-airflow
