### ISSUE TITLE
webserver-1 keep crashing

### ISSUE THREAD

**Issue by charlietls** [tuanavu/airflow-tutorial#63]
My env is Windows 10 + docker desktop:

Step 1:  git clone https://github.com/tuanavu/airflow-tutorial.git
Step 2:  cd airflow-tutorial
Step 3:  docker-compose up
>>>>>
airflow-tutorial-webserver-1  | /usr/local/lib/python3.6/site-packages/airflow/configuration.py:57: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
airflow-tutorial-webserver-1  |   from cryptography.fernet import Fernet
airflow-tutorial-webserver-1  | Traceback (most recent call last):
airflow-tutorial-webserver-1  |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/__init__.py", line 18, in <module>
airflow-tutorial-webserver-1  |     from . import _mysql
airflow-tutorial-webserver-1  | ImportError: libmariadb.so.3: cannot open shared object file: No such file or directory
airflow-tutorial-webserver-1  |
airflow-tutorial-webserver-1  | During handling of the above exception, another exception occurred:
airflow-tutorial-webserver-1  |
airflow-tutorial-webserver-1  | Traceback (most recent call last):
airflow-tutorial-webserver-1  |   File "/usr/local/bin/airflow", line 21, in <module>
airflow-tutorial-webserver-1  |     from airflow import configuration
airflow-tutorial-webserver-1  |   File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 36, in <module>
airflow-tutorial-webserver-1  |     from airflow import settings
airflow-tutorial-webserver-1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 261, in <module>
airflow-tutorial-webserver-1  |     configure_adapters()
airflow-tutorial-webserver-1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 218, in configure_adapters
airflow-tutorial-webserver-1  |     import MySQLdb.converters
airflow-tutorial-webserver-1  |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/__init__.py", line 24, in <module>
airflow-tutorial-webserver-1  |     version_info, _mysql.version_info, _mysql.__file__
airflow-tutorial-webserver-1  | NameError: name '_mysql' is not defined
airflow-tutorial-webserver-1  | Traceback (most recent call last):
airflow-tutorial-webserver-1  |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/__init__.py", line 18, in <module>
airflow-tutorial-webserver-1  |     from . import _mysql
airflow-tutorial-webserver-1  | ImportError: libmariadb.so.3: cannot open shared object file: No such file or directory

**Comment by KiranQureshi53** [comment]
Hey, it has been fixed in the below mentioned link 
[https://github.com/tuanavu/airflow-tutorial/issues/51#issuecomment-918743193]
