### ISSUE TITLE
getting following error when i tried to start the docker container for the tutorial

### ISSUE THREAD

**Issue by oauthtester01** [tuanavu/airflow-tutorial#65]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/airflow", line 21, in <module>
    from airflow import configuration
  File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 36, in <module>
    from airflow import settings
  File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 261, in <module>
    configure_adapters()
  File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 218, in configure_adapters
    import MySQLdb.converters
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/__init__.py", line 24, in <module>
    version_info, _mysql.version_info, _mysql.__file__
NameError: name '_mysql' is not defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/MySQLdb/__init__.py", line 18, in <module>
    from . import _mysql
ImportError: libmariadb.so.3: cannot open shared object file: No such file or directory

**Comment by ngarg-panw** [comment]
Getting the same.

**Comment by atrotsik** [comment]
Same

**Comment by sevkw** [comment]
same here.
